version: "3"
services:
    api_server:
        image: fastfi/api:latest
        ports:
            - "6000:6000"
        networks:
            - fastfi
        depends_on:
            - mongo
    mongo:
        image: mongo
        ports:
            - "27017:27017"
        networks:
            - fastfi
        volumes:
            - mongo-data:/data/db
networks:
    fastfi:
        driver: bridge
volumes:
    mongo-data:
        driver: local
