version: "3"
services:
    api_server:
        image: fastfi/api:latest
        ports:
            - "5000:5000"
        networks:
            - fastfi
        depends_on:
            - mongo
    react:
        image: fastfi/react:latest
        ports:
            - "80:80"
        networks:
            - fastfi
        depends_on:
            - api_server
    mongo:
        image: mongo
        ports:
            - "27017:27017"
        networks:
            - fastfi
        volumes:
            - mongo-data:/data/db
networks:
    fastfi:
        driver: bridge
volumes:
    mongo-data:
        driver: local
